server:
  host: "localhost"
  port: 8000
  portfrontend: "http://localhost:3000"
  keypassword: ""

database:
  username: ""
  password: "@"
  name: ""
  host: ""
  port:

Cache:
  username: ""
  password: ""
  host: ""
  port:

gmail:
  host: "smtp.gmail.com"
  port:
  service: "gmail"
  mail: ""
  password: ""
