server:
  host: "localhost"
  port: 8000

database:
  username: ""
  password: ""
  name: ""
  host: ""
  port:

Cache:
  username: ""
  password: ""
  host: ""
  port:

gmail:
  host: "smtp.gmail.com"
  port: 465
  service: "gmail"
  mail: "example@gmail.com"
  password: "Nguyen Tien Tai"
